import type { Metadata } from "next";
import { Bebas_Neue, Space_Grotesk } from "next/font/google";
import Navbar from "./(components)/Navbar";
import "./globals.css";

// Alternative to Tusker - bold display font
const bebasNeue = Bebas_Neue({
  weight: "400",
  variable: "--font-tusker",
  subsets: ["latin"],
});

// Alternative to ClashDisplay - modern geometric sans
const spaceGrotesk = Space_Grotesk({
  variable: "--font-clash",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
